### ISSUE TITLE
How to switch audio inputs/outputs on OS X

### ISSUE THREAD

**Issue by dhowe** [orsjb/beads#21]
Trying to figure out how to specify the audio-system and then (hopefully) the specific audio inputs/outputs to use...

OSX 10.13
jackd 0.125.0 

```
AudioContext : no AudioIO specified, using default => net.beadsproject.beads.core.io.JavaSoundAudioIO.
JavaSoundAudioIO: Chosen mixer is Default Audio Device.
CHOSEN INPUT: interface TargetDataLine supporting 14 audio formats, and buffers of at least 32 bytes, buffer size in bytes: 5000
```

**Comment by orsjb** [comment]
Are you getting audio?
What version of Java are you using? We’ve noticed some audio config issues with Java 10 (possibly 9 as well).
Are you trying to use Jack in this instance?
I actually need to check in with Angelo Fraietta who has set up a default static AudioContext, about how a specific AudioContext should now be set.

Ollie

**Comment by dhowe** [comment]
Thanks... I am getting audio. I wanted to specify inputs and outputs, and the docs I found suggested doing this via jack, which I have installed. But none of that jack config tools seem to maintained for recent OS X versions.

Anyhow, the goal is just to be able to specify inputs and outputs for my Beads app

**Comment by orsjb** [comment]
Yes Jack OSX support is super super confusing — it does work but it is often unclear what the state of support is, and there are some hacks involved. It’s high time Beads had its own multichannel IO (hmm, I mean it would be really NICE if Java wanted to support that at the JVM, after all it is 2019). I can talk you through the process for getting Beads running through Jack, and once you’ve got it set up it is quite pleasant and functional, but right now I’m scratching my head about when I last did this. 

Ollie

**Comment by dhowe** [comment]
> I can talk you through the process for getting Beads running through Jack

that would be fantastic, thanks

**Comment by whizkid79** [comment]
That would be interesting for me too. Is there some written tutorial somewhere, which is up to date?

**Comment by orsjb** [comment]
Nothing online, no.
Gosh it’s been a very long time now since I’ve done this. Very rusty. I’m also not sure of Jack’s status. I recall that there were some version-related issues, but it does work if you get it set up right.

Roughly, from memory…

Install Jack and configure. Run it from commandline using jackd or jackdmp or use JackPilot. Get familiar with how Jack works if you don’t know (e.g., try running it and connecting different programs together).
In your Beads program, when you set up your AudioContext, you should create a Jack AudioIO using something like "new AudioServerIO.Jack()”. So the AudioContext setup code looks something like:

AudioContext ac = new AudioContext(new AudioServerIO.Jack());

(There will be some other arguments specifying the data format, channels etc).

One thing you need to get right is to make sure the AudioContext’s buffer size matches Jack’s buffer size. If they don’t match Jack will reject the connection.

Now when you run your Beads program it should automatically connect to Jack and you should see Beads appear in the JackPilot program. That’s your proof of concept that it works. Once that’s working you can experiment with setting up multiple channels and different configs.

As a bonus look at the experimental class called net.beadsproject.beads.core.JackRemote (under the beads_io src). This gives some functionality which allows you to remotely operate Jack, including starting it. It does this by summoning shell calls. You can also write run scripts that run Jack and then run your Beads program if you want to.

Don’t forget to let us know what you’re using Beads for.

Best,

Ollie
