### ISSUE TITLE
Cannot update to 3.2

### ISSUE THREAD

**Issue by PhlegmingChee** [orsjb/beads#30]
The Contribution Manager in Processing 3.5.4 shows an available update for Beads to 3.2 but the update doesn't seem to update at all and Beads still shows as 1.02.

**Comment by rbnpi** [comment]
I have this problem too. How can I install 3.2 in Processing?

**Comment by vdurnev** [comment]
Actually update installed successfully, but because beads/packages/Processing/library.porperties was not updated in the distribution for processing you still see that new 3.2 update is available.
As a quick fix you can edit  <processing folder>/libraries/beads/library.properties:
version=3
prettyVersion=3.2

After restart of processing you should not see beads library in the list of available updates.

**Comment by jeremydouglass** [comment]
Beads release 3.2 is broken in Processing, because the beads package doesn't show the correct release when manually installed, as @vdurnev says.

How to fix with a release 3.2.1 in three steps.

1. bump the package internal library.properties file with the correct version information.

```
# counter, counting the total number of releases you've had.
version = 4  # This must be parsable as an int

# The version as the user will see it. If blank, the version attribute will be used here
prettyVersion = 3.2.1  # This is treated as a String
```

2. build a new release.
3. copy **BOTH** 
    -   library.properties --> http://beadsproject.net/library/beads.txt
    -   the release zip to --> http://beadsproject.net/library/beads.zip

Note that the public properties file and zip filename must match exactly -- Processing PDE derives the zip name from the properties name.

You fixed it!

Now, when PDE contribution manager tries to check beads for an update, it will:

1. look up the library catalog at: https://raw.githubusercontent.com/processing/processing-docs/master/contrib_generate/sources.conf
2. find the properties entry at http://beadsproject.net/library/beads.txt, which says "4 / 3.2.1"
3. version=4 is greater than 3 (or 1), so:
4. give you an update button
4. download the corresponding zip from beads.zip
5. check its internal library.properties -- which is "4 / 3.2.1", so install will continue.
6. when it is done, correctly (!) display that "3.2.1" was updated

**Comment by orsjb** [comment]
Great work Jeremy. Thank you.
I’ve made those changes at beadsproject.net/library/beads.txt. 
I can’t recall if Processing pull this file from here. I think they do, so this should resolve it.
Always keen to add contributors to the github repo if you want to get stuck in and make fixes.

**Comment by PhlegmingChee** [comment]
Thanks. This fix works on MacOS. My Windows setup on the other hand... but I'm thinking because I have a non-standard My Documents folder setup so there may be a path issue. When I remove Beads from Processing's Tools menu the location I though Beads would be installed would have the directory removed. It doesn't. When I manually remove it and install it again, Beads does not show up in that directory. Ergo it must be in a different path, or my Windows version of Processing is borked.

Also, the Beads pulled down by Processing on MacOS still contains the incorrect library.properties file.
________________________________

**Comment by jeremydouglass** [comment]
Hi @orsjb -- thank you for the merge! However, you have not completed the fix, because it cannot be done solely in source code. As per the instructions on this issue and on my pull request, you still need to:

2. build a new release (!!!!) tagged 3.2.1 -- it should be added to your github releases
3. copy BOTH:
    -   library.properties --> http://beadsproject.net/library/beads.txt
    -   the release zip to --> http://beadsproject.net/library/beads.zip

If you don't do (2), manual installs from this repo will still show errors. If you don't do both parts of (3), PDE Downloads from github repo will still be wrong.

Sorry for all the instructions. I'm happy to help with releasing if you want me to join the repo.

Re:

> I can’t recall if Processing pull this file from here.

They do -- you can look up the library catalog at: https://raw.githubusercontent.com/processing/processing-docs/master/contrib_generate/sources.conf and see that is the lookup entry that they have for beads.

**Comment by orsjb** [comment]
Thanks Jeremy! Don’t apologies for clear instructions! You’re a star.
My ability to maintain this project has waned. The gradle build has been through a few hands and I haven’t touched it in ages, and my gradle is rusty at the best of times! There are a couple of errors that I need to fix on my install to run it. Meanwhile I will add you to the repo if you’re interested, but of course no expectations. Ditto if anyone else wants to get in touch and help revive this project they are welcome. It would be great to keep this alive if people are using it.

**Comment by jeremydouglass** [comment]
Sure, please add me. I don't have gradle set up on this machine right now, but I can give it a quick look.
