### ISSUE TITLE
Publish to Maven Central Repository

### ISSUE THREAD

**Issue by ceefour** [orsjb/beads#5]
It would be great if Beads library can be published to Maven Central Repository, this will help a lot to make it easier to add Beads library in a project.

Sonatype provides free hosting : http://central.sonatype.org/pages/ossrh-guide.html

**Comment by orsjb** [comment]
Hi Hendy,

I’m up for that. Can you help me set this up?

**Comment by Sciss** [comment]
Hi. Just seeing your project, code looks good and clean, I'd like to use it, so having it on Maven Central would be great. ceefour has the link to the description how to setup the account with Sonatype. Unfortunately it's a bit of a PITA the first time.

Related question: Readme says "GNU Public License", would that be GPL or LGPL, and which version, like GPL v2+, LGPL v2.1+? Thanks

**Comment by orsjb** [comment]
Hi Hans,

I’d love to get it on Maven. I don’t know how but can follow instructions. I don’t have any time now. Maybe in June. If you can help I would welcome that.

The license is GPL. I haven’t actually chosen a version. Another thing in my TODO list is to learn the differences. For now I am not too fussed, just give attribution, keep open, ask me if you want to use it in a commercial closed source project.

Ollie

**Comment by oletizi** [comment]
I've created a pom.xml for beads that allows you to compile and install beads (as a single jar with all dependencies included) into your local repo. This isn't enough to get it published to maven central, but it will make it a LOT easier to integrate it into other maven projects.

Here's a patch file for my changes:

  http://media.orionletizi.com/beads_pom.patch

To apply it, download the patch and run this from the beads project directory:

  git apply path/to/beads_pom.patch

I've attached a patchfile with the pom.xml in it. Once you apply the patch, to install beads in your local repo, do this:

  mvn install

Cheers,
--Orion

**Comment by orsjb** [comment]
Hi Orion,

thanks. I have actually updated the Beads build file so that it jarjars all of the jar files into a single one. It's prettier :-) But I assume what you are giving us here is additionally useful.

> I've attached a patchfile with the pom.xml in it. 

Where is pom.xml? Attached where?

> to install beads in your local repo.

Can you just clarify what you mean by "local repo" here? This is probably mavenspeak that I'm not familiar with.

As ever, I will endeavour to (very slowly) get to this, but if you do want to send a pull request that's cool. I am keen to have more hands on keeping the library alive. And do please tell me what you're using it for.

**Comment by orsjb** [comment]
@Sciss, I've updated the readme to say GPL v2+.

**Comment by juzweb** [comment]
Hi orsjb,

Maven is like a database of jars (libraries). When you install maven, it will create so call a directory call .m2.  This .m2 folder will be your local repo. When you run any maven project that depends on external jars specified in the pom.xml file, Maven will download it and install in the local repo, provided you have uploaded the jar into the global repo such as sonatype. 

Maven also has a method call mavenise. In which you create an empty maven project that encapsulate your jar file. When you compile and install this maven project, it will install into your local repo. Hope this helps.

**Comment by rossdrew** [comment]
Just looking at using this in [my NES emulator,](https://github.com/rossdrew/emuRox) would be great if I could just add it to dependencies.

**Comment by orsjb** [comment]
I’ve just had a student interested in taking this on. It might happen.

**Comment by cwong4311** [comment]
Sorry for the wait. As of early last month, we've finally been able to get Beads up on Maven Central.

You can find it [here](https://search.maven.org/artifact/net.beadsproject/beads/3.1/jar) as well as in the git README.
Unfortunately, due to a few issues during the uploading process, the license is incorrectly stated as Apache. 
It will be corrected to GPL (v3) in the coming release.

I will be closing this issue as the original request has been fulfilled. If you have any other questions, please let us know and we'll be happy to help.

Best
Charlton
